import { DevtoolsDetector } from './classes/devtools-detector';
import { DevtoolsDetectorListener } from './types/devtools-detector-listener.type';
import * as checkers from './checkers/checkers';
declare const defaultDetector: DevtoolsDetector;
export declare function addListener(listener: DevtoolsDetectorListener): void;
export declare function removeListener(listener: DevtoolsDetectorListener): void;
export declare function isLaunch(): boolean;
export declare function launch(): void;
export declare function stop(): void;
export declare function setDetectDelay(time: number): void;
export default defaultDetector;
export { DevtoolsDetail } from './types/devtools-detail.type';
export { DevtoolsDetectorListener } from './types/devtools-detector-listener.type';
export { DevtoolsStatusChecker } from './types/devtools-status-checker.type';
export { DevtoolsDetector, checkers };
export { match, specificVersionMatch } from './shared/utils';
export * from './shared/context';
export * from './shared/console';
export * from './shared/version-map';
export * from './shared/system-info';
